services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - meta_app_data:/app/data
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.meta-results-m.entrypoints=websecure
      - traefik.http.routers.meta-results-m.rule=Host(`ads.ozmo.media`)
      - traefik.http.routers.meta-results-m.tls.certresolver=lets
      - traefik.http.services.meta-results-m.loadbalancer.server.port=3000
    networks:
      - default
      - web

volumes:
  meta_app_data:

networks:
  web:
    external: true
